-- This module is the root of the InvariantSubspaceProblemCanonicalLaneLean Lean proof package.
import InvariantSubspaceProblemCanonicalLaneLean.Basic
import InvariantSubspaceProblemCanonicalLaneLean.SourcePackage
import InvariantSubspaceProblemCanonicalLaneLean.SourceDependencies
import InvariantSubspaceProblemCanonicalLaneLean.Formalization
import InvariantSubspaceProblemCanonicalLaneLean.ReviewerBridge
import InvariantSubspaceProblemCanonicalLaneLean.TheoremStatement
import InvariantSubspaceProblemCanonicalLaneLean.MathlibObjects
import InvariantSubspaceProblemCanonicalLaneLean.AdmissibleClass
import InvariantSubspaceProblemCanonicalLaneLean.Projection
import InvariantSubspaceProblemCanonicalLaneLean.BridgeLemmas
import InvariantSubspaceProblemCanonicalLaneLean.GateLemmas
import InvariantSubspaceProblemCanonicalLaneLean.FinalTheorem
import InvariantSubspaceProblemCanonicalLaneLean.MathlibStatement
